version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 45s
    command: nginx -g 'daemon off;'
    networks:
      - node-net
    ports:
      - '8080:80'
    depends_on:
      - db
      - app

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node index.js
    tty: true
    volumes:
      - ./app:/usr/src/app
    networks:
      - node-net
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/mysql:/var/lib/mysql
    networks:
      - node-net

networks:
  node-net:
    driver: bridge
